import argparse
import base64
from collections import defaultdict, deque
import hashlib
import hmac
import json
import os
import re
import secrets
import sqlite3
import struct
import threading
import time
from datetime import datetime, timedelta
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit


BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "licencas.sqlite"
ENV_PATH = BASE_DIR / ".env"
PRODUCTS = {
    "igt_individual": "Iguatu Individual",
    "jua_individual": "Juazeiro Individual",
    "jua_emp": "Juazeiro Empreendimento",
}
SERVICE_VERSION = "2026-09-29-admin-session"
SERVER_SIGNATURE_FIELDS = ("license_key", "machine_id", "product", "ok", "status", "expires_at", "customer", "message", "issued_at")
LICENSE_KEY_RE = re.compile(r"^DOCFLOW-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}$")
MACHINE_ID_RE = re.compile(r"^[0-9A-F]{32}$")
MAX_POST_BYTES = 16 * 1024
RATE_LIMIT_WINDOW = 60
RATE_LIMIT_MAX = 80
RATE_LIMITS = defaultdict(deque)
ADMIN_LOGIN_ATTEMPTS = defaultdict(deque)
ADMIN_LOGIN_WINDOW = 5 * 60
ADMIN_LOGIN_MAX = 5
ADMIN_SESSIONS = {}
ADMIN_SESSION_CSRF = {}
ADMIN_SESSION_LOCK = threading.Lock()
ADMIN_LAST_TOTP_COUNTER = -1


def load_env_file():
    if not ENV_PATH.exists():
        return
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip().lstrip("\ufeff"), value.strip().strip('"').strip("'"))


load_env_file()


def license_private_key():
    n = os.getenv("DOCFLOW_LICENSE_PRIVATE_N", "").strip()
    d = os.getenv("DOCFLOW_LICENSE_PRIVATE_D", "").strip()
    if not n or not d:
        raise RuntimeError("DOCFLOW_LICENSE_PRIVATE_N/D ausente no ambiente.")
    return int(n), int(d)


def database_url():
    url = os.getenv("DATABASE_URL", "").strip()
    if url.startswith("postgres") and "sslmode=" not in url:
        url += ("&" if "?" in url else "?") + "sslmode=require"
    return url


def using_postgres():
    return database_url().startswith("postgres")


def sql(text):
    return text.replace("?", "%s") if using_postgres() else text


def connect():
    url = database_url()
    if url.startswith("postgres"):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except Exception as exc:
            raise RuntimeError("Instale psycopg: pip install psycopg[binary]") from exc
        return psycopg.connect(url, row_factory=dict_row)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def today():
    return datetime.now().date()


def add_months(base_date, months):
    return base_date + timedelta(days=30 * int(months))


def add_period(base_date, months=0, days=0):
    return base_date + timedelta(days=(30 * int(months)) + int(days))


def payment_grace_days():
    try:
        return max(0, int(os.getenv("PAYMENT_GRACE_DAYS", "3") or 0))
    except Exception:
        return 3


def normalize_product(value):
    product = str(value or "").strip().lower()
    return product if product in PRODUCTS else ""


def init_db():
    if using_postgres():
        usage_id = "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    else:
        usage_id = "id INTEGER PRIMARY KEY AUTOINCREMENT"
    with connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS licenses (
                license_key TEXT PRIMARY KEY,
                product TEXT NOT NULL DEFAULT 'igt_individual',
                customer TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'active',
                expires_at TEXT NOT NULL,
                max_machines INTEGER NOT NULL DEFAULT 1,
                daily_limit INTEGER NOT NULL DEFAULT 0,
                notes TEXT DEFAULT '',
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS activations (
                license_key TEXT NOT NULL,
                machine_id TEXT NOT NULL,
                first_seen TEXT NOT NULL,
                last_seen TEXT NOT NULL,
                PRIMARY KEY (license_key, machine_id)
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS activation_aliases (
                license_key TEXT NOT NULL,
                machine_id TEXT NOT NULL,
                activation_machine_id TEXT NOT NULL,
                created_at TEXT NOT NULL,
                PRIMARY KEY (license_key, machine_id),
                UNIQUE (license_key, activation_machine_id)
            )
            """
        )
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS usage_events (
                {usage_id},
                license_key TEXT NOT NULL,
                machine_id TEXT NOT NULL,
                product TEXT NOT NULL DEFAULT '',
                event TEXT NOT NULL,
                details TEXT DEFAULT '',
                created_at TEXT NOT NULL
            )
            """
        )
        if using_postgres():
            conn.execute("ALTER TABLE licenses ADD COLUMN IF NOT EXISTS product TEXT NOT NULL DEFAULT 'igt_individual'")
            conn.execute("ALTER TABLE licenses ADD COLUMN IF NOT EXISTS daily_limit INTEGER NOT NULL DEFAULT 0")
            conn.execute("ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS product TEXT NOT NULL DEFAULT ''")
        else:
            ensure_sqlite_column(conn, "licenses", "product", "TEXT NOT NULL DEFAULT 'igt_individual'")
            ensure_sqlite_column(conn, "licenses", "daily_limit", "INTEGER NOT NULL DEFAULT 0")
            ensure_sqlite_column(conn, "usage_events", "product", "TEXT NOT NULL DEFAULT ''")


def ensure_sqlite_column(conn, table, column, definition):
    columns = [row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()]
    if column not in columns:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def signature_payload(data):
    payload = {field: data.get(field, "") for field in SERVER_SIGNATURE_FIELDS}
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def sign_response(data, payload):
    data = dict(data)
    data.setdefault("license_key", str(payload.get("license_key", "")).strip().upper())
    data.setdefault("machine_id", str(payload.get("machine_id", "")).strip().upper())
    data.setdefault("product", normalize_product(payload.get("product")))
    data.setdefault("issued_at", datetime.now().isoformat(timespec="seconds"))
    digest_info = bytes.fromhex("3031300d060960864801650304020105000420") + hashlib.sha256(signature_payload(data)).digest()
    private_n, private_d = license_private_key()
    key_len = (private_n.bit_length() + 7) // 8
    padded = b"\x00\x01" + (b"\xff" * (key_len - len(digest_info) - 3)) + b"\x00" + digest_info
    signature = pow(int.from_bytes(padded, "big"), private_d, private_n).to_bytes(key_len, "big")
    data["signature"] = base64.urlsafe_b64encode(signature).decode("ascii")
    return data


def make_key():
    return "DOCFLOW-" + "-".join(secrets.token_hex(2).upper() for _ in range(4))


def get_license(conn, license_key, lock=False):
    query = "SELECT * FROM licenses WHERE license_key = ?"
    if lock and using_postgres():
        query += " FOR UPDATE"
    return conn.execute(sql(query), (license_key,)).fetchone()


def normalize_machine_id(value):
    machine = str(value or "").strip().upper()
    return machine if re.fullmatch(r"[A-F0-9]{32}", machine) else ""


def _fingerprint_v2(stable_value):
    normalized = "".join(ch for ch in str(stable_value or "").upper() if ch.isalnum())
    if not normalized:
        return ""
    raw = f"DOCFLOW-MACHINE-V2|{normalized}".encode("ascii", "ignore")
    return hashlib.sha256(raw).hexdigest().upper()[:32]


def verified_legacy_machine_id(payload, current):
    proof = payload.get("migration_proof") or {}
    if not isinstance(proof, dict):
        return ""
    source = str(proof.get("source", "")).strip().lower()
    stable_value = str(proof.get("stable_value", "")).strip()
    hostname = str(proof.get("hostname", "")).strip()
    node = str(proof.get("node", "")).strip()
    claimed = normalize_machine_id(proof.get("legacy_machine_id"))
    if source not in {"machine_guid", "uuid", "mac"}:
        return ""
    if not stable_value or len(stable_value) > 256 or "|" in stable_value:
        return ""
    if not hostname or len(hostname) > 255 or "|" in hostname:
        return ""
    if not re.fullmatch(r"\d{1,20}", node):
        return ""
    if int(node) < 0 or int(node) > 0xFFFFFFFFFFFF:
        return ""
    expected_current = _fingerprint_v2(stable_value)
    if not expected_current or not secrets.compare_digest(expected_current, current):
        return ""
    parts = [stable_value, hostname, node] if source == "machine_guid" else [hostname, node]
    expected_legacy = hashlib.sha256("|".join(parts).encode("utf-8", "ignore")).hexdigest().upper()[:32]
    if not claimed or not secrets.compare_digest(expected_legacy, claimed):
        return ""
    return claimed


def find_activation_machine(conn, license_key, machine_id):
    direct = conn.execute(
        sql("SELECT machine_id FROM activations WHERE license_key = ? AND machine_id = ?"),
        (license_key, machine_id),
    ).fetchone()
    if direct:
        return direct["machine_id"]
    alias = conn.execute(
        sql("SELECT activation_machine_id FROM activation_aliases WHERE license_key = ? AND machine_id = ?"),
        (license_key, machine_id),
    ).fetchone()
    return alias["activation_machine_id"] if alias else ""


def add_activation_alias(conn, license_key, machine_id, legacy_machine_id, now):
    legacy = conn.execute(
        sql("SELECT machine_id FROM activations WHERE license_key = ? AND machine_id = ?"),
        (license_key, legacy_machine_id),
    ).fetchone()
    if not legacy:
        return ""
    if using_postgres():
        query = """
            INSERT INTO activation_aliases (license_key, machine_id, activation_machine_id, created_at)
            VALUES (?, ?, ?, ?) ON CONFLICT DO NOTHING
        """
    else:
        query = """
            INSERT OR IGNORE INTO activation_aliases
            (license_key, machine_id, activation_machine_id, created_at) VALUES (?, ?, ?, ?)
        """
    conn.execute(sql(query), (license_key, machine_id, legacy_machine_id, now))
    mapped = conn.execute(
        sql("SELECT activation_machine_id FROM activation_aliases WHERE license_key = ? AND machine_id = ?"),
        (license_key, machine_id),
    ).fetchone()
    if mapped and secrets.compare_digest(mapped["activation_machine_id"], legacy_machine_id):
        return mapped["activation_machine_id"]
    return ""


def license_response(payload, activate=False):
    init_db()
    license_key = str(payload.get("license_key", "")).strip().upper()
    machine_id = normalize_machine_id(payload.get("machine_id"))
    product = normalize_product(payload.get("product"))
    now = datetime.now().isoformat(timespec="seconds")
    if not license_key or not machine_id:
        return {"ok": False, "status": "invalid", "message": "Chave ou maquina ausente.", "product": product}
    if not LICENSE_KEY_RE.match(license_key):
        return {"ok": False, "status": "invalid", "message": "Formato de chave invalido.", "product": product}
    if not MACHINE_ID_RE.match(machine_id):
        return {"ok": False, "status": "invalid_machine", "message": "Identificador de maquina invalido.", "product": product}
    if not product:
        return {"ok": False, "status": "invalid_product", "message": "Produto ausente ou invalido.", "product": product}
    with connect() as conn:
        if not using_postgres():
            conn.execute("BEGIN IMMEDIATE")
        row = get_license(conn, license_key, lock=True)
        if not row:
            return {"ok": False, "status": "invalid", "message": "Licenca nao encontrada.", "product": product}
        if row["product"] != product:
            return {
                "ok": False,
                "status": "product_mismatch",
                "message": f"Licenca pertence a {PRODUCTS.get(row['product'], row['product'])}.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        status = row["status"]
        expires = datetime.strptime(row["expires_at"], "%Y-%m-%d").date()
        if status != "active":
            return {
                "ok": False,
                "status": status,
                "message": f"Licenca {status}.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        activation_machine_id = find_activation_machine(conn, license_key, machine_id)
        if not activation_machine_id:
            legacy_machine_id = verified_legacy_machine_id(payload, machine_id)
            if legacy_machine_id:
                activation_machine_id = add_activation_alias(
                    conn, license_key, machine_id, legacy_machine_id, now
                )
        expired = expires < today()
        if not activation_machine_id and activate and not expired:
            count = conn.execute(
                sql("SELECT COUNT(*) AS total FROM activations WHERE license_key = ?"),
                (license_key,),
            ).fetchone()["total"]
            if count >= int(row["max_machines"]):
                return {
                    "ok": False,
                    "status": "machine_limit",
                    "message": "Limite de maquinas atingido.",
                    "customer": row["customer"],
                    "expires_at": row["expires_at"],
                    "product": product,
                }
            conn.execute(
                sql("INSERT INTO activations (license_key, machine_id, first_seen, last_seen) VALUES (?, ?, ?, ?)"),
                (license_key, machine_id, now, now),
            )
            activation_machine_id = machine_id
        elif activation_machine_id:
            conn.execute(
                sql("UPDATE activations SET last_seen = ? WHERE license_key = ? AND machine_id = ?"),
                (now, license_key, activation_machine_id),
            )
        else:
            return {
                "ok": False,
                "status": "not_activated",
                "message": "Maquina nao ativada para esta licenca.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        if expired:
            grace_days = payment_grace_days()
            grace_until = expires + timedelta(days=grace_days)
            if grace_days and grace_until >= today():
                return {
                    "ok": True,
                    "status": "active",
                    "message": f"Licenca vencida em {expires.strftime('%d/%m/%Y')}. Tolerancia ate {grace_until.strftime('%d/%m/%Y')}.",
                    "customer": row["customer"],
                    "expires_at": row["expires_at"],
                    "product": product,
                }
            return {
                "ok": False,
                "status": "expired",
                "message": f"Licenca vencida em {expires.strftime('%d/%m/%Y')}.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        daily_limit = int(row["daily_limit"] or 0) if "daily_limit" in row.keys() else 0
        if daily_limit > 0 and not activate:
            day_start = datetime.combine(today(), datetime.min.time()).isoformat(timespec="seconds")
            day_end = datetime.combine(today() + timedelta(days=1), datetime.min.time()).isoformat(timespec="seconds")
            used_today = conn.execute(
                sql("""
                    SELECT COUNT(*) AS total
                    FROM usage_events
                    WHERE license_key = ? AND product = ? AND event = 'generation_start'
                      AND created_at >= ? AND created_at < ?
                """),
                (license_key, product, day_start, day_end),
            ).fetchone()["total"]
            if used_today >= daily_limit:
                return {
                    "ok": False,
                    "status": "daily_limit",
                    "message": f"Limite diario atingido ({daily_limit}/dia).",
                    "customer": row["customer"],
                    "expires_at": row["expires_at"],
                    "product": product,
                }
        return {
            "ok": True,
            "status": "active",
            "message": f"Licenca ativa ate {expires.strftime('%d/%m/%Y')}.",
            "customer": row["customer"],
            "expires_at": row["expires_at"],
            "product": product,
        }


def usage_response(payload):
    response = license_response(payload, activate=False)
    if response.get("ok"):
        product = normalize_product(payload.get("product"))
        with connect() as conn:
            conn.execute(
                sql("INSERT INTO usage_events (license_key, machine_id, product, event, details, created_at) VALUES (?, ?, ?, ?, ?, ?)"),
                (
                    str(payload.get("license_key", "")).strip().upper(),
                    str(payload.get("machine_id", "")).strip().upper(),
                    product,
                    str(payload.get("event", "usage")).strip()[:80] or "usage",
                    json.dumps(payload.get("details") or {}, ensure_ascii=False),
                    datetime.now().isoformat(timespec="seconds"),
                ),
            )
        response["message"] = "Uso registrado."
    return response


def make_admin_password_hash(password, salt=None):
    if len(str(password or "")) < 12:
        raise ValueError("Senha administrativa deve ter pelo menos 12 caracteres.")
    salt = salt or secrets.token_bytes(16)
    n, r, p = 16384, 8, 1
    digest = hashlib.scrypt(str(password).encode("utf-8"), salt=salt, n=n, r=r, p=p, dklen=32)
    return "scrypt${}${}${}${}${}".format(
        n, r, p,
        base64.urlsafe_b64encode(salt).decode("ascii").rstrip("="),
        base64.urlsafe_b64encode(digest).decode("ascii").rstrip("="),
    )


def verify_admin_password(password):
    encoded = os.getenv("FORJA_ADMIN_PASSWORD_HASH", "").strip()
    try:
        algorithm, n, r, p, salt_text, digest_text = encoded.split("$", 5)
        if algorithm != "scrypt":
            return False
        salt = base64.urlsafe_b64decode(salt_text + "=" * (-len(salt_text) % 4))
        expected = base64.urlsafe_b64decode(digest_text + "=" * (-len(digest_text) % 4))
        actual = hashlib.scrypt(
            str(password or "").encode("utf-8"),
            salt=salt,
            n=int(n), r=int(r), p=int(p), dklen=len(expected),
        )
        return hmac.compare_digest(actual, expected)
    except Exception:
        return False


def _totp_secret_bytes():
    secret = re.sub(r"\s+", "", os.getenv("FORJA_ADMIN_TOTP_SECRET", "")).upper()
    if len(secret) < 16 or not re.fullmatch(r"[A-Z2-7]+", secret):
        return b""
    try:
        return base64.b32decode(secret + "=" * (-len(secret) % 8), casefold=True)
    except Exception:
        return b""


def admin_totp_code(counter, secret_bytes=None):
    secret_bytes = secret_bytes or _totp_secret_bytes()
    digest = hmac.new(secret_bytes, struct.pack(">Q", int(counter)), hashlib.sha1).digest()
    offset = digest[-1] & 0x0F
    value = (struct.unpack(">I", digest[offset:offset + 4])[0] & 0x7FFFFFFF) % 1000000
    return f"{value:06d}"


def verify_admin_totp(code, now=None):
    code = str(code or "").strip()
    secret_bytes = _totp_secret_bytes()
    if not secret_bytes or not re.fullmatch(r"\d{6}", code):
        return None
    counter = int((time.time() if now is None else now) // 30)
    for candidate in (counter - 1, counter, counter + 1):
        if hmac.compare_digest(admin_totp_code(candidate, secret_bytes), code):
            return candidate
    return None


def admin_auth_configured():
    return bool(os.getenv("FORJA_ADMIN_PASSWORD_HASH", "").strip()) and bool(_totp_secret_bytes())


def _admin_session_seconds():
    try:
        return min(3600, max(300, int(os.getenv("FORJA_ADMIN_SESSION_SECONDS", "1800"))))
    except Exception:
        return 1800


def create_admin_session(password, totp_code):
    global ADMIN_LAST_TOTP_COUNTER
    if not admin_auth_configured():
        return None
    password_ok = verify_admin_password(password)
    counter = verify_admin_totp(totp_code)
    if not password_ok or counter is None:
        return None
    with ADMIN_SESSION_LOCK:
        if counter <= ADMIN_LAST_TOTP_COUNTER:
            return None
        ADMIN_LAST_TOTP_COUNTER = counter
        now = time.time()
        expired = [key for key, expires in ADMIN_SESSIONS.items() if expires <= now]
        for key in expired:
            ADMIN_SESSIONS.pop(key, None)
            ADMIN_SESSION_CSRF.pop(key, None)
        token = secrets.token_urlsafe(32)
        token_hash = hashlib.sha256(token.encode("ascii")).hexdigest()
        ADMIN_SESSIONS[token_hash] = now + _admin_session_seconds()
        ADMIN_SESSION_CSRF[token_hash] = secrets.token_urlsafe(24)
    return token


def admin_session_valid(token):
    if not token:
        return False
    token_hash = hashlib.sha256(str(token).encode("utf-8")).hexdigest()
    with ADMIN_SESSION_LOCK:
        expires = ADMIN_SESSIONS.get(token_hash, 0)
        if expires <= time.time():
            ADMIN_SESSIONS.pop(token_hash, None)
            ADMIN_SESSION_CSRF.pop(token_hash, None)
            return False
    return True


def discard_admin_session(token):
    token_hash = hashlib.sha256(str(token or "").encode("utf-8")).hexdigest()
    with ADMIN_SESSION_LOCK:
        ADMIN_SESSIONS.pop(token_hash, None)
        ADMIN_SESSION_CSRF.pop(token_hash, None)


def admin_session_csrf(token):
    if not admin_session_valid(token):
        return ""
    token_hash = hashlib.sha256(str(token).encode("utf-8")).hexdigest()
    with ADMIN_SESSION_LOCK:
        return ADMIN_SESSION_CSRF.get(token_hash, "")


def _admin_license_data(row):
    expires_at = str(row["expires_at"] or "")
    try:
        days_remaining = (datetime.strptime(expires_at, "%Y-%m-%d").date() - today()).days
    except Exception:
        days_remaining = None
    return {
        "license_key": row["license_key"], "product": row["product"],
        "customer": row["customer"], "status": row["status"],
        "created_at": row["created_at"], "expires_at": expires_at,
        "days_remaining": days_remaining, "max_machines": row["max_machines"],
        "machines": row["machines"] if "machines" in row.keys() else 0,
    }


def admin_list_licenses(search=""):
    search = str(search or "").strip()
    where, params = "", []
    if search:
        where = "WHERE UPPER(l.license_key) LIKE ? OR LOWER(l.customer) LIKE ?"
        params = [f"%{search.upper()}%", f"%{search.lower()}%"]
    with connect() as conn:
        rows = conn.execute(sql(f"""
            SELECT l.license_key, l.product, l.customer, l.status, l.created_at,
                   l.expires_at, l.max_machines, COUNT(a.machine_id) AS machines
            FROM licenses l LEFT JOIN activations a ON a.license_key = l.license_key
            {where}
            GROUP BY l.license_key, l.product, l.customer, l.status, l.created_at,
                     l.expires_at, l.max_machines
            ORDER BY l.created_at DESC
        """), params).fetchall()
    return [_admin_license_data(row) for row in rows]


def admin_get_license(license_key):
    key = str(license_key or "").strip().upper()
    with connect() as conn:
        row = conn.execute(sql("""
            SELECT l.license_key, l.product, l.customer, l.status, l.created_at,
                   l.expires_at, l.max_machines, COUNT(a.machine_id) AS machines
            FROM licenses l LEFT JOIN activations a ON a.license_key = l.license_key
            WHERE l.license_key = ?
            GROUP BY l.license_key, l.product, l.customer, l.status, l.created_at,
                     l.expires_at, l.max_machines
        """), (key,)).fetchone()
    return _admin_license_data(row) if row else None


def _admin_parse_date(value):
    try:
        return datetime.strptime(str(value or ""), "%Y-%m-%d").date().isoformat()
    except Exception as exc:
        raise ValueError("Data invalida. Use AAAA-MM-DD.") from exc


def admin_create_license(payload):
    customer = str(payload.get("customer", "")).strip()
    product = normalize_product(payload.get("product"))
    expires_at = _admin_parse_date(payload.get("expires_at"))
    try:
        max_machines = int(payload.get("max_machines", 1))
    except Exception as exc:
        raise ValueError("Limite de maquinas invalido.") from exc
    if not customer or not product or max_machines < 1:
        raise ValueError("Dados da licenca invalidos.")
    key = make_key()
    with connect() as conn:
        conn.execute(sql("""
            INSERT INTO licenses
            (license_key, product, customer, status, expires_at, max_machines, daily_limit, notes, created_at)
            VALUES (?, ?, ?, 'active', ?, ?, 0, ?, ?)
        """), (key, product, customer, expires_at, max_machines,
                 str(payload.get("notes", ""))[:500], datetime.now().isoformat(timespec="seconds")))
    return admin_get_license(key)


def admin_update_license(license_key, payload):
    key = str(license_key or "").strip().upper()
    if not admin_get_license(key):
        return None
    updates, params = [], []
    if "expires_at" in payload:
        updates.append("expires_at = ?")
        params.append(_admin_parse_date(payload.get("expires_at")))
    if "status" in payload:
        status = str(payload.get("status", "")).strip().lower()
        if status not in {"active", "blocked"}:
            raise ValueError("Status invalido.")
        updates.append("status = ?")
        params.append(status)
    if not updates:
        raise ValueError("Nenhuma alteracao valida informada.")
    with connect() as conn:
        conn.execute(sql(f"UPDATE licenses SET {', '.join(updates)} WHERE license_key = ?"), (*params, key))
    return admin_get_license(key)


def admin_list_activations(license_key):
    key = str(license_key or "").strip().upper()
    if not admin_get_license(key):
        return None
    with connect() as conn:
        rows = conn.execute(sql("""
            SELECT machine_id, first_seen, last_seen FROM activations
            WHERE license_key = ? ORDER BY last_seen DESC
        """), (key,)).fetchall()
    return [dict(row) for row in rows]


def admin_unlink_activation(license_key, machine_id):
    key = str(license_key or "").strip().upper()
    machine = normalize_machine_id(machine_id)
    if not machine:
        raise ValueError("Identificador de maquina invalido.")
    with connect() as conn:
        row = conn.execute(sql("SELECT 1 FROM activations WHERE license_key = ? AND machine_id = ?"), (key, machine)).fetchone()
        if not row:
            return False
        conn.execute(sql("DELETE FROM activation_aliases WHERE license_key = ? AND (machine_id = ? OR activation_machine_id = ?)"), (key, machine, machine))
        conn.execute(sql("DELETE FROM activations WHERE license_key = ? AND machine_id = ?"), (key, machine))
    return True


def admin_audit(operation, license_key=""):
    print(json.dumps({"event": "admin_audit", "operation": str(operation),
                      "license_key": str(license_key or "").upper(),
                      "created_at": datetime.now().isoformat(timespec="seconds")},
                     ensure_ascii=False), flush=True)


class LicenseHandler(BaseHTTPRequestHandler):
    def _client_ip(self):
        forwarded = self.headers.get("X-Forwarded-For", "")
        if forwarded:
            return forwarded.split(",", 1)[0].strip()
        return self.client_address[0] if self.client_address else "unknown"

    def _rate_limited(self):
        key = (self._client_ip(), self.path)
        now = time.time()
        bucket = RATE_LIMITS[key]
        while bucket and now - bucket[0] > RATE_LIMIT_WINDOW:
            bucket.popleft()
        if len(bucket) >= RATE_LIMIT_MAX:
            return True
        bucket.append(now)
        return False

    def _send(self, status, data, headers=None):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        for name, value in (headers or {}).items():
            self.send_header(name, value)
        self.end_headers()
        self.wfile.write(body)

    def _send_asset(self, path, content_type):
        try:
            body = path.read_bytes()
        except OSError:
            self._send(404, {"ok": False, "message": "Nao encontrado."})
            return
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'")
        self.end_headers()
        self.wfile.write(body)

    def _read_admin_json(self):
        length = int(self.headers.get("Content-Length", "0") or 0)
        if length > MAX_POST_BYTES:
            raise ValueError("Requisicao grande demais.")
        try:
            payload = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
        except Exception as exc:
            raise ValueError("JSON invalido.") from exc
        if not isinstance(payload, dict):
            raise ValueError("JSON invalido.")
        return payload

    def _bearer_token(self):
        authorization = self.headers.get("Authorization", "").strip()
        if authorization.lower().startswith("bearer "):
            return authorization[7:].strip()
        try:
            cookie = SimpleCookie()
            cookie.load(self.headers.get("Cookie", ""))
            morsel = cookie.get("forja_admin_session")
            return morsel.value if morsel else ""
        except Exception:
            return ""

    def _using_cookie_session(self):
        return not self.headers.get("Authorization", "").lower().startswith("bearer ") and bool(self._bearer_token())

    def _require_admin_session(self):
        if not admin_session_valid(self._bearer_token()):
            self._send(401, {"ok": False, "message": "Sessao administrativa invalida ou expirada."})
            return False
        return True

    def _require_admin_csrf(self):
        if not self._using_cookie_session():
            return True
        supplied = self.headers.get("X-CSRF-Token", "").strip()
        expected = admin_session_csrf(self._bearer_token())
        if not supplied or not expected or not hmac.compare_digest(supplied, expected):
            self._send(403, {"ok": False, "message": "Protecao CSRF invalida."})
            return False
        return True

    def _login_limited(self):
        now = time.time()
        bucket = ADMIN_LOGIN_ATTEMPTS[self._client_ip()]
        while bucket and now - bucket[0] > ADMIN_LOGIN_WINDOW:
            bucket.popleft()
        if len(bucket) >= ADMIN_LOGIN_MAX:
            return True
        bucket.append(now)
        return False

    def _admin_parts(self):
        parsed = urlsplit(self.path)
        return parsed, [unquote(part) for part in parsed.path.strip("/").split("/") if part]

    def _admin_failure(self, exc):
        print(f"admin_error={type(exc).__name__}", flush=True)
        self._send(500, {"ok": False, "message": "Falha ao acessar administracao."})

    def _handle_admin_login(self, web=False):
        if self._login_limited():
            self._send(429, {"ok": False, "message": "Muitas tentativas. Aguarde."})
            return
        if not admin_auth_configured():
            self._send(503, {"ok": False, "message": "Autenticacao administrativa nao configurada."})
            return
        try:
            payload = self._read_admin_json()
        except ValueError as exc:
            self._send(400, {"ok": False, "message": str(exc)})
            return
        token = create_admin_session(payload.get("password"), payload.get("totp"))
        if not token:
            self._send(401, {"ok": False, "message": "Credenciais invalidas."})
            return
        admin_audit("login")
        if web:
            max_age = _admin_session_seconds()
            cookie = f"forja_admin_session={token}; Path=/admin; Max-Age={max_age}; HttpOnly; Secure; SameSite=Strict"
            self._send(200, {"ok": True, "csrf_token": admin_session_csrf(token), "expires_in": max_age}, {"Set-Cookie": cookie})
        else:
            self._send(200, {"ok": True, "session_token": token, "expires_in": _admin_session_seconds()})

    def _handle_admin_get(self):
        if not self._require_admin_session():
            return
        parsed, parts = self._admin_parts()
        try:
            if parts == ["admin", "licenses"]:
                search = parse_qs(parsed.query).get("search", [""])[0]
                licenses = admin_list_licenses(search)
                self._send(200, {"ok": True, "licenses": licenses, "count": len(licenses)})
            elif len(parts) == 3 and parts[:2] == ["admin", "licenses"]:
                item = admin_get_license(parts[2])
                self._send(200, {"ok": True, "license": item}) if item else self._send(404, {"ok": False, "message": "Licenca nao encontrada."})
            elif len(parts) == 4 and parts[:2] == ["admin", "licenses"] and parts[3] == "activations":
                items = admin_list_activations(parts[2])
                self._send(200, {"ok": True, "activations": items, "count": len(items)}) if items is not None else self._send(404, {"ok": False, "message": "Licenca nao encontrada."})
            else:
                self._send(404, {"ok": False, "message": "Rota administrativa nao encontrada."})
        except Exception as exc:
            self._admin_failure(exc)

    def _handle_admin_create(self):
        if not self._require_admin_session() or not self._require_admin_csrf():
            return
        try:
            item = admin_create_license(self._read_admin_json())
            admin_audit("create_license", item["license_key"])
            self._send(201, {"ok": True, "license": item})
        except ValueError as exc:
            self._send(400, {"ok": False, "message": str(exc)})
        except Exception as exc:
            self._admin_failure(exc)

    def _handle_admin_patch(self):
        if not self._require_admin_session() or not self._require_admin_csrf():
            return
        _parsed, parts = self._admin_parts()
        if len(parts) != 3 or parts[:2] != ["admin", "licenses"]:
            self._send(404, {"ok": False, "message": "Rota administrativa nao encontrada."})
            return
        try:
            payload = self._read_admin_json()
            item = admin_update_license(parts[2], payload)
            if not item:
                self._send(404, {"ok": False, "message": "Licenca nao encontrada."})
                return
            operation = "change_expiration" if "expires_at" in payload else ("block_license" if payload.get("status") == "blocked" else "unblock_license")
            admin_audit(operation, parts[2])
            self._send(200, {"ok": True, "license": item})
        except ValueError as exc:
            self._send(400, {"ok": False, "message": str(exc)})
        except Exception as exc:
            self._admin_failure(exc)

    def _handle_admin_delete(self):
        if not self._require_admin_session() or not self._require_admin_csrf():
            return
        _parsed, parts = self._admin_parts()
        if len(parts) != 5 or parts[:2] != ["admin", "licenses"] or parts[3] != "activations":
            self._send(404, {"ok": False, "message": "Rota administrativa nao encontrada."})
            return
        try:
            if not admin_unlink_activation(parts[2], parts[4]):
                self._send(404, {"ok": False, "message": "Ativacao nao encontrada."})
                return
            admin_audit("unlink_activation", parts[2])
            self._send(200, {"ok": True, "message": "Maquina desvinculada."})
        except ValueError as exc:
            self._send(400, {"ok": False, "message": str(exc)})
        except Exception as exc:
            self._admin_failure(exc)

    def do_GET(self):
        parsed_path = urlsplit(self.path).path
        if parsed_path in {"/admin", "/admin/"}:
            self._send_asset(BASE_DIR / "admin_web.html", "text/html; charset=utf-8")
        elif parsed_path == "/admin/admin.css":
            self._send_asset(BASE_DIR / "admin_web.css", "text/css; charset=utf-8")
        elif parsed_path == "/admin/admin.js":
            self._send_asset(BASE_DIR / "admin_web.js", "application/javascript; charset=utf-8")
        elif parsed_path == "/admin/session":
            if not self._require_admin_session():
                return
            self._send(200, {"ok": True, "csrf_token": admin_session_csrf(self._bearer_token()), "expires_in": _admin_session_seconds()})
        elif self.path.startswith("/admin/"):
            if self._rate_limited():
                self._send(429, {"ok": False, "message": "Muitas tentativas. Aguarde."})
                return
            self._handle_admin_get()
        elif self.path == "/health":
            self._send(200, {
                "ok": True,
                "service": "docflow-license",
                "version": SERVICE_VERSION,
                "db": "postgres" if using_postgres() else "sqlite",
            })
        else:
            self._send(404, {"ok": False, "message": "Nao encontrado."})

    def do_POST(self):
        if self._rate_limited():
            self._send(429, {"ok": False, "message": "Muitas tentativas. Aguarde."})
            return
        if self.path == "/admin/login":
            self._handle_admin_login()
            return
        if self.path == "/admin/web-login":
            self._handle_admin_login(web=True)
            return
        if self.path == "/admin/logout":
            if not self._require_admin_session() or not self._require_admin_csrf():
                return
            discard_admin_session(self._bearer_token())
            admin_audit("logout")
            self._send(200, {"ok": True})
            return
        if self.path == "/admin/web-logout":
            if not self._require_admin_session() or not self._require_admin_csrf():
                return
            discard_admin_session(self._bearer_token())
            admin_audit("logout")
            expired = "forja_admin_session=; Path=/admin; Max-Age=0; HttpOnly; Secure; SameSite=Strict"
            self._send(200, {"ok": True}, {"Set-Cookie": expired})
            return
        if self.path == "/admin/licenses":
            self._handle_admin_create()
            return
        length = int(self.headers.get("Content-Length", "0") or 0)
        if length > MAX_POST_BYTES:
            self._send(413, {"ok": False, "message": "Requisicao grande demais."})
            return
        try:
            payload = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
        except Exception:
            self._send(400, {"ok": False, "message": "JSON invalido."})
            return
        if self.path == "/activate":
            self._send(200, sign_response(license_response(payload, activate=True), payload))
        elif self.path == "/validate":
            self._send(200, sign_response(license_response(payload, activate=False), payload))
        elif self.path == "/usage":
            self._send(200, sign_response(usage_response(payload), payload))
        else:
            self._send(404, {"ok": False, "message": "Nao encontrado."})

    def do_PATCH(self):
        if self._rate_limited():
            self._send(429, {"ok": False, "message": "Muitas tentativas. Aguarde."})
            return
        if self.path.startswith("/admin/licenses/"):
            self._handle_admin_patch()
        else:
            self._send(404, {"ok": False, "message": "Nao encontrado."})

    def do_DELETE(self):
        if self._rate_limited():
            self._send(429, {"ok": False, "message": "Muitas tentativas. Aguarde."})
            return
        if self.path.startswith("/admin/licenses/"):
            self._handle_admin_delete()
        else:
            self._send(404, {"ok": False, "message": "Nao encontrado."})

    def log_message(self, fmt, *args):
        print("%s - %s" % (self._client_ip(), fmt % args))


def cmd_create(args):
    init_db()
    product = normalize_product(args.product)
    if not product:
        raise SystemExit("Produto invalido. Use: " + ", ".join(PRODUCTS))
    key = (args.key or make_key()).upper()
    if not LICENSE_KEY_RE.match(key):
        raise SystemExit("Formato de chave invalido.")
    expires = add_period(today(), args.months, args.days).strftime("%Y-%m-%d")
    with connect() as conn:
        conn.execute(
            sql(
                """
                INSERT INTO licenses (license_key, product, customer, status, expires_at, max_machines, daily_limit, notes, created_at)
                VALUES (?, ?, ?, 'active', ?, ?, ?, ?, ?)
                """
            ),
            (key, product, args.customer, expires, args.max_machines, args.daily_limit, args.notes or "", datetime.now().isoformat(timespec="seconds")),
        )
    print(json.dumps({"license_key": key, "product": product, "customer": args.customer, "expires_at": expires}, ensure_ascii=False, indent=2))


def cmd_renew(args):
    init_db()
    key = args.key.upper()
    with connect() as conn:
        row = get_license(conn, key)
        if not row:
            raise SystemExit("Licenca nao encontrada.")
        current = datetime.strptime(row["expires_at"], "%Y-%m-%d").date()
        base = max(current, today())
        expires = add_period(base, args.months, args.days).strftime("%Y-%m-%d")
        conn.execute(sql("UPDATE licenses SET status = 'active', expires_at = ? WHERE license_key = ?"), (expires, key))
    print(f"Renovada: {key} ate {expires}")


def cmd_status(args, status):
    init_db()
    with connect() as conn:
        conn.execute(sql("UPDATE licenses SET status = ? WHERE license_key = ?"), (status, args.key.upper()))
    print(f"{args.key.upper()}: {status}")


def cmd_delete(args):
    init_db()
    key = args.key.upper()
    with connect() as conn:
        row = get_license(conn, key)
        if not row:
            raise SystemExit("Licenca nao encontrada.")
        conn.execute(sql("DELETE FROM activations WHERE license_key = ?"), (key,))
        conn.execute(sql("DELETE FROM usage_events WHERE license_key = ?"), (key,))
        conn.execute(sql("DELETE FROM licenses WHERE license_key = ?"), (key,))
    print(json.dumps({"license_key": key, "deleted": True}, ensure_ascii=False, indent=2))


def cmd_daily_limit(args):
    init_db()
    key = args.key.upper()
    if args.limit < 0:
        raise SystemExit("Limite precisa ser zero ou maior.")
    with connect() as conn:
        row = get_license(conn, key)
        if not row:
            raise SystemExit("Licenca nao encontrada.")
        conn.execute(sql("UPDATE licenses SET daily_limit = ? WHERE license_key = ?"), (args.limit, key))
    print(json.dumps({"license_key": key, "daily_limit": args.limit}, ensure_ascii=False, indent=2))


def cmd_list(_args):
    init_db()
    with connect() as conn:
        rows = conn.execute(
            sql(
                """
                SELECT l.license_key, l.product, l.customer, l.status, l.expires_at, l.max_machines, l.daily_limit,
                       COUNT(a.machine_id) AS machines
                FROM licenses l
                LEFT JOIN activations a ON a.license_key = l.license_key
                GROUP BY l.license_key, l.product, l.customer, l.status, l.expires_at, l.max_machines, l.daily_limit, l.created_at
                ORDER BY l.created_at DESC
                """
            )
        ).fetchall()
    if not rows:
        print("Nenhuma chave encontrada.")
        return
    for row in rows:
        daily = row["daily_limit"] if "daily_limit" in row.keys() else 0
        daily_text = "sem limite" if not daily else f"{daily}/dia"
        print(f"{row['license_key']} | {row['product']} | {row['customer']} | {row['status']} | vence {row['expires_at']} | maquinas {row['machines']}/{row['max_machines']} | uso {daily_text}")


def _format_usage_datetime(value):
    try:
        return datetime.fromisoformat(str(value).replace("Z", "")).strftime("%d/%m/%Y %H:%M")
    except Exception:
        return str(value)


def _format_usage_event(value):
    labels = {
        "generation_start": "Geracao iniciada",
        "usage": "Uso",
    }
    return labels.get(str(value or ""), str(value or "-"))


def _format_usage_details(value):
    try:
        data = json.loads(value or "{}")
    except Exception:
        return str(value or "-")
    if not isinstance(data, dict) or not data:
        return "-"
    parts = []
    if data.get("cliente"):
        parts.append(f"cliente={data.get('cliente')}")
    if data.get("modo"):
        parts.append(f"modo={data.get('modo')}")
    if data.get("total_documentos") is not None:
        parts.append(f"docs={data.get('total_documentos')}")
    docs = data.get("documentos")
    if isinstance(docs, list) and docs:
        preview = ", ".join(str(item) for item in docs[:4])
        if len(docs) > 4:
            preview += f", +{len(docs) - 4}"
        parts.append(f"selecionados={preview}")
    return " | ".join(parts) if parts else json.dumps(data, ensure_ascii=False)


def cmd_usage(args):
    init_db()
    params = []
    clauses = []
    if args.key:
        clauses.append("license_key = ?")
        params.append(args.key.upper())
    if args.product:
        product = normalize_product(args.product)
        if not product:
            raise SystemExit("Produto invalido.")
        clauses.append("product = ?")
        params.append(product)
    with connect() as conn:
        if clauses:
            query = "SELECT license_key, machine_id, product, event, details, created_at FROM usage_events WHERE " + " AND ".join(clauses) + " ORDER BY id DESC LIMIT ?"  # nosec B608
        else:
            query = "SELECT license_key, machine_id, product, event, details, created_at FROM usage_events ORDER BY id DESC LIMIT ?"
        rows = conn.execute(
            sql(query),
            (*params, args.limit),
        ).fetchall()
    if not rows:
        print("Nenhum uso registrado.")
        return
    totals = {}
    for row in rows:
        key = (row["license_key"], row["product"], row["event"])
        totals[key] = totals.get(key, 0) + 1
    print("RESUMO")
    for (license_key, product, event), total in sorted(totals.items(), key=lambda item: item[1], reverse=True):
        print(f"- {product} | {license_key} | {_format_usage_event(event)}: {total}")
    print("\nHISTORICO")
    print("Data/hora        | Produto        | Chave                   | Maquina  | Evento            | Detalhes")
    print("-" * 120)
    for row in rows:
        machine_short = str(row["machine_id"] or "")[:8]
        print(
            f"{_format_usage_datetime(row['created_at']):16} | "
            f"{str(row['product'] or '-')[:14]:14} | "
            f"{str(row['license_key'] or '-')[:23]:23} | "
            f"{machine_short:8} | "
            f"{_format_usage_event(row['event'])[:17]:17} | "
            f"{_format_usage_details(row['details'])}"
        )


def cmd_products(_args):
    for key, name in PRODUCTS.items():
        print(f"{key} | {name}")


def cmd_serve(args):
    init_db()
    port = int(args.port or os.getenv("PORT", "8787"))
    server = ThreadingHTTPServer((args.host, port), LicenseHandler)
    print(f"Servidor de licencas em http://{args.host}:{port}")
    server.serve_forever()


def main():
    parser = argparse.ArgumentParser(description="Servidor de licencas DocFlow SIOPI")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init")
    sub.add_parser("products")

    create = sub.add_parser("create")
    create.add_argument("--customer", required=True)
    create.add_argument("--product", required=True, choices=sorted(PRODUCTS))
    create.add_argument("--months", type=int, default=1)
    create.add_argument("--days", type=int, default=0)
    create.add_argument("--max-machines", type=int, default=1)
    create.add_argument("--daily-limit", type=int, default=0)
    create.add_argument("--notes", default="")
    create.add_argument("--key")

    renew = sub.add_parser("renew")
    renew.add_argument("--key", required=True)
    renew.add_argument("--months", type=int, default=1)
    renew.add_argument("--days", type=int, default=0)

    block = sub.add_parser("block")
    block.add_argument("--key", required=True)

    unblock = sub.add_parser("unblock")
    unblock.add_argument("--key", required=True)

    delete = sub.add_parser("delete")
    delete.add_argument("--key", required=True)

    daily_limit = sub.add_parser("daily-limit")
    daily_limit.add_argument("--key", required=True)
    daily_limit.add_argument("--limit", type=int, required=True)

    sub.add_parser("list")

    usage = sub.add_parser("usage")
    usage.add_argument("--key")
    usage.add_argument("--product", choices=sorted(PRODUCTS))
    usage.add_argument("--limit", type=int, default=50)

    serve = sub.add_parser("serve")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int)

    args = parser.parse_args()
    if args.cmd == "init":
        init_db()
        print("Banco pronto: postgres" if using_postgres() else f"Banco pronto: {DB_PATH}")
    elif args.cmd == "products":
        cmd_products(args)
    elif args.cmd == "create":
        cmd_create(args)
    elif args.cmd == "renew":
        cmd_renew(args)
    elif args.cmd == "block":
        cmd_status(args, "blocked")
    elif args.cmd == "unblock":
        cmd_status(args, "active")
    elif args.cmd == "delete":
        cmd_delete(args)
    elif args.cmd == "daily-limit":
        cmd_daily_limit(args)
    elif args.cmd == "list":
        cmd_list(args)
    elif args.cmd == "usage":
        cmd_usage(args)
    elif args.cmd == "serve":
        cmd_serve(args)


if __name__ == "__main__":
    main()

