import argparse
import base64
import hashlib
import json
import os
import secrets
import sqlite3
from datetime import datetime, timedelta
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "licencas.sqlite"
ENV_PATH = BASE_DIR / ".env"
PRODUCTS = {
    "igt_individual": "Iguatu Individual",
    "jua_individual": "Juazeiro Individual",
    "jua_emp": "Juazeiro Empresa",
}
SERVER_PRIVATE_N = 106537066273957117313240081191464501776242139540655222201529619101456358428722342219026162145204400278649468892608116521900175108380436076142564087603617812966525658915872695062426607701605335357569720938503943724353653006144864421556018622385064111695239492576954703686891896730872157517023773123420441223623
SERVER_PRIVATE_D = 94491356810752786335454875862737951000925078125023514974873921136310080510037743353606874391783209103209754464205441034354509338615280037199426624962013692837704055071583450879156276390289359042163872344010887756878358144148264090362487014248204716759664880869180292151124282841031671103215732400326777800953
SERVER_SIGNATURE_FIELDS = ("license_key", "machine_id", "product", "ok", "status", "expires_at", "customer", "message", "issued_at")


def load_env_file():
    if not ENV_PATH.exists():
        return
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip().lstrip("\ufeff"), value.strip().strip('"').strip("'"))


load_env_file()


def database_url():
    url = os.getenv("DATABASE_URL", "").strip()
    if url.startswith("postgres") and "sslmode=" not in url:
        url += ("&" if "?" in url else "?") + "sslmode=require"
    return url


def using_postgres():
    return database_url().startswith("postgres")


def sql(text):
    return text.replace("?", "%s") if using_postgres() else text


def connect():
    url = database_url()
    if url.startswith("postgres"):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except Exception as exc:
            raise RuntimeError("Instale psycopg: pip install psycopg[binary]") from exc
        return psycopg.connect(url, row_factory=dict_row)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def today():
    return datetime.now().date()


def add_months(base_date, months):
    return base_date + timedelta(days=30 * int(months))


def add_period(base_date, months=0, days=0):
    return base_date + timedelta(days=(30 * int(months)) + int(days))


def payment_grace_days():
    try:
        return max(0, int(os.getenv("PAYMENT_GRACE_DAYS", "3") or 0))
    except Exception:
        return 3


def normalize_product(value):
    product = str(value or "").strip().lower()
    return product if product in PRODUCTS else ""


def init_db():
    if using_postgres():
        usage_id = "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    else:
        usage_id = "id INTEGER PRIMARY KEY AUTOINCREMENT"
    with connect() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS licenses (
                license_key TEXT PRIMARY KEY,
                product TEXT NOT NULL DEFAULT 'igt_individual',
                customer TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'active',
                expires_at TEXT NOT NULL,
                max_machines INTEGER NOT NULL DEFAULT 1,
                notes TEXT DEFAULT '',
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS activations (
                license_key TEXT NOT NULL,
                machine_id TEXT NOT NULL,
                first_seen TEXT NOT NULL,
                last_seen TEXT NOT NULL,
                PRIMARY KEY (license_key, machine_id)
            )
            """
        )
        conn.execute(
            f"""
            CREATE TABLE IF NOT EXISTS usage_events (
                {usage_id},
                license_key TEXT NOT NULL,
                machine_id TEXT NOT NULL,
                product TEXT NOT NULL DEFAULT '',
                event TEXT NOT NULL,
                details TEXT DEFAULT '',
                created_at TEXT NOT NULL
            )
            """
        )
        if using_postgres():
            conn.execute("ALTER TABLE licenses ADD COLUMN IF NOT EXISTS product TEXT NOT NULL DEFAULT 'igt_individual'")
            conn.execute("ALTER TABLE usage_events ADD COLUMN IF NOT EXISTS product TEXT NOT NULL DEFAULT ''")
        else:
            ensure_sqlite_column(conn, "licenses", "product", "TEXT NOT NULL DEFAULT 'igt_individual'")
            ensure_sqlite_column(conn, "usage_events", "product", "TEXT NOT NULL DEFAULT ''")


def ensure_sqlite_column(conn, table, column, definition):
    columns = [row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()]
    if column not in columns:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def signature_payload(data):
    payload = {field: data.get(field, "") for field in SERVER_SIGNATURE_FIELDS}
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def sign_response(data, payload):
    data = dict(data)
    data.setdefault("license_key", str(payload.get("license_key", "")).strip().upper())
    data.setdefault("machine_id", str(payload.get("machine_id", "")).strip().upper())
    data.setdefault("product", normalize_product(payload.get("product")))
    data.setdefault("issued_at", datetime.now().isoformat(timespec="seconds"))
    digest_info = bytes.fromhex("3031300d060960864801650304020105000420") + hashlib.sha256(signature_payload(data)).digest()
    key_len = (SERVER_PRIVATE_N.bit_length() + 7) // 8
    padded = b"\x00\x01" + (b"\xff" * (key_len - len(digest_info) - 3)) + b"\x00" + digest_info
    signature = pow(int.from_bytes(padded, "big"), SERVER_PRIVATE_D, SERVER_PRIVATE_N).to_bytes(key_len, "big")
    data["signature"] = base64.urlsafe_b64encode(signature).decode("ascii")
    return data


def make_key():
    return "DOCFLOW-" + "-".join(secrets.token_hex(2).upper() for _ in range(4))


def get_license(conn, license_key):
    return conn.execute(sql("SELECT * FROM licenses WHERE license_key = ?"), (license_key,)).fetchone()


def license_response(payload, activate=False):
    init_db()
    license_key = str(payload.get("license_key", "")).strip().upper()
    machine_id = str(payload.get("machine_id", "")).strip().upper()
    product = normalize_product(payload.get("product"))
    now = datetime.now().isoformat(timespec="seconds")
    if not license_key or not machine_id:
        return {"ok": False, "status": "invalid", "message": "Chave ou maquina ausente.", "product": product}
    if not product:
        return {"ok": False, "status": "invalid_product", "message": "Produto ausente ou invalido.", "product": product}
    with connect() as conn:
        row = get_license(conn, license_key)
        if not row:
            return {"ok": False, "status": "invalid", "message": "Licenca nao encontrada.", "product": product}
        if row["product"] != product:
            return {
                "ok": False,
                "status": "product_mismatch",
                "message": f"Licenca pertence a {PRODUCTS.get(row['product'], row['product'])}.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        status = row["status"]
        expires = datetime.strptime(row["expires_at"], "%Y-%m-%d").date()
        if status != "active":
            return {
                "ok": False,
                "status": status,
                "message": f"Licenca {status}.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        if expires < today():
            grace_days = payment_grace_days()
            grace_until = expires + timedelta(days=grace_days)
            if grace_days and grace_until >= today():
                return {
                    "ok": True,
                    "status": "active",
                    "message": f"Licenca vencida em {expires.strftime('%d/%m/%Y')}. Tolerancia ate {grace_until.strftime('%d/%m/%Y')}.",
                    "customer": row["customer"],
                    "expires_at": row["expires_at"],
                    "product": product,
                }
            return {
                "ok": False,
                "status": "expired",
                "message": f"Licenca vencida em {expires.strftime('%d/%m/%Y')}.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        exists = conn.execute(
            sql("SELECT 1 FROM activations WHERE license_key = ? AND machine_id = ?"),
            (license_key, machine_id),
        ).fetchone()
        if not exists and activate:
            count = conn.execute(
                sql("SELECT COUNT(*) AS total FROM activations WHERE license_key = ?"),
                (license_key,),
            ).fetchone()["total"]
            if count >= int(row["max_machines"]):
                return {
                    "ok": False,
                    "status": "machine_limit",
                    "message": "Limite de maquinas atingido.",
                    "customer": row["customer"],
                    "expires_at": row["expires_at"],
                    "product": product,
                }
            conn.execute(
                sql("INSERT INTO activations (license_key, machine_id, first_seen, last_seen) VALUES (?, ?, ?, ?)"),
                (license_key, machine_id, now, now),
            )
        elif exists:
            conn.execute(
                sql("UPDATE activations SET last_seen = ? WHERE license_key = ? AND machine_id = ?"),
                (now, license_key, machine_id),
            )
        elif not activate:
            return {
                "ok": False,
                "status": "not_activated",
                "message": "Maquina nao ativada para esta licenca.",
                "customer": row["customer"],
                "expires_at": row["expires_at"],
                "product": product,
            }
        return {
            "ok": True,
            "status": "active",
            "message": f"Licenca ativa ate {expires.strftime('%d/%m/%Y')}.",
            "customer": row["customer"],
            "expires_at": row["expires_at"],
            "product": product,
        }


def usage_response(payload):
    response = license_response(payload, activate=False)
    if response.get("ok"):
        product = normalize_product(payload.get("product"))
        with connect() as conn:
            conn.execute(
                sql("INSERT INTO usage_events (license_key, machine_id, product, event, details, created_at) VALUES (?, ?, ?, ?, ?, ?)"),
                (
                    str(payload.get("license_key", "")).strip().upper(),
                    str(payload.get("machine_id", "")).strip().upper(),
                    product,
                    str(payload.get("event", "usage")).strip()[:80] or "usage",
                    json.dumps(payload.get("details") or {}, ensure_ascii=False),
                    datetime.now().isoformat(timespec="seconds"),
                ),
            )
        response["message"] = "Uso registrado."
    return response


class LicenseHandler(BaseHTTPRequestHandler):
    def _send(self, status, data):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/health":
            self._send(200, {"ok": True, "service": "docflow-license", "db": "postgres" if using_postgres() else "sqlite"})
        else:
            self._send(404, {"ok": False, "message": "Nao encontrado."})

    def do_POST(self):
        length = min(int(self.headers.get("Content-Length", "0") or 0), 1024 * 1024)
        try:
            payload = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
        except Exception:
            self._send(400, {"ok": False, "message": "JSON invalido."})
            return
        if self.path == "/activate":
            self._send(200, sign_response(license_response(payload, activate=True), payload))
        elif self.path == "/validate":
            self._send(200, sign_response(license_response(payload, activate=False), payload))
        elif self.path == "/usage":
            self._send(200, sign_response(usage_response(payload), payload))
        else:
            self._send(404, {"ok": False, "message": "Nao encontrado."})

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args))


def cmd_create(args):
    init_db()
    product = normalize_product(args.product)
    if not product:
        raise SystemExit("Produto invalido. Use: " + ", ".join(PRODUCTS))
    key = (args.key or make_key()).upper()
    expires = add_period(today(), args.months, args.days).strftime("%Y-%m-%d")
    with connect() as conn:
        conn.execute(
            sql(
                """
                INSERT INTO licenses (license_key, product, customer, status, expires_at, max_machines, notes, created_at)
                VALUES (?, ?, ?, 'active', ?, ?, ?, ?)
                """
            ),
            (key, product, args.customer, expires, args.max_machines, args.notes or "", datetime.now().isoformat(timespec="seconds")),
        )
    print(json.dumps({"license_key": key, "product": product, "customer": args.customer, "expires_at": expires}, ensure_ascii=False, indent=2))


def cmd_renew(args):
    init_db()
    key = args.key.upper()
    with connect() as conn:
        row = get_license(conn, key)
        if not row:
            raise SystemExit("Licenca nao encontrada.")
        current = datetime.strptime(row["expires_at"], "%Y-%m-%d").date()
        base = max(current, today())
        expires = add_period(base, args.months, args.days).strftime("%Y-%m-%d")
        conn.execute(sql("UPDATE licenses SET status = 'active', expires_at = ? WHERE license_key = ?"), (expires, key))
    print(f"Renovada: {key} ate {expires}")


def cmd_status(args, status):
    init_db()
    with connect() as conn:
        conn.execute(sql("UPDATE licenses SET status = ? WHERE license_key = ?"), (status, args.key.upper()))
    print(f"{args.key.upper()}: {status}")


def cmd_list(_args):
    init_db()
    with connect() as conn:
        rows = conn.execute(
            sql(
                """
                SELECT l.license_key, l.product, l.customer, l.status, l.expires_at, l.max_machines,
                       COUNT(a.machine_id) AS machines
                FROM licenses l
                LEFT JOIN activations a ON a.license_key = l.license_key
                GROUP BY l.license_key, l.product, l.customer, l.status, l.expires_at, l.max_machines, l.created_at
                ORDER BY l.created_at DESC
                """
            )
        ).fetchall()
    for row in rows:
        print(f"{row['license_key']} | {row['product']} | {row['customer']} | {row['status']} | vence {row['expires_at']} | maquinas {row['machines']}/{row['max_machines']}")


def cmd_usage(args):
    init_db()
    params = []
    clauses = []
    if args.key:
        clauses.append("license_key = ?")
        params.append(args.key.upper())
    if args.product:
        product = normalize_product(args.product)
        if not product:
            raise SystemExit("Produto invalido.")
        clauses.append("product = ?")
        params.append(product)
    where = "WHERE " + " AND ".join(clauses) if clauses else ""
    with connect() as conn:
        rows = conn.execute(
            sql(f"SELECT license_key, machine_id, product, event, details, created_at FROM usage_events {where} ORDER BY id DESC LIMIT ?"),
            (*params, args.limit),
        ).fetchall()
    for row in rows:
        print(f"{row['created_at']} | {row['product']} | {row['license_key']} | {row['machine_id']} | {row['event']} | {row['details']}")


def cmd_products(_args):
    for key, name in PRODUCTS.items():
        print(f"{key} | {name}")


def cmd_serve(args):
    init_db()
    port = int(args.port or os.getenv("PORT", "8787"))
    server = ThreadingHTTPServer((args.host, port), LicenseHandler)
    print(f"Servidor de licencas em http://{args.host}:{port}")
    server.serve_forever()


def main():
    parser = argparse.ArgumentParser(description="Servidor de licencas DocFlow SIOPI")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init")
    sub.add_parser("products")

    create = sub.add_parser("create")
    create.add_argument("--customer", required=True)
    create.add_argument("--product", required=True, choices=sorted(PRODUCTS))
    create.add_argument("--months", type=int, default=1)
    create.add_argument("--days", type=int, default=0)
    create.add_argument("--max-machines", type=int, default=1)
    create.add_argument("--notes", default="")
    create.add_argument("--key")

    renew = sub.add_parser("renew")
    renew.add_argument("--key", required=True)
    renew.add_argument("--months", type=int, default=1)
    renew.add_argument("--days", type=int, default=0)

    block = sub.add_parser("block")
    block.add_argument("--key", required=True)

    unblock = sub.add_parser("unblock")
    unblock.add_argument("--key", required=True)

    sub.add_parser("list")

    usage = sub.add_parser("usage")
    usage.add_argument("--key")
    usage.add_argument("--product", choices=sorted(PRODUCTS))
    usage.add_argument("--limit", type=int, default=50)

    serve = sub.add_parser("serve")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int)

    args = parser.parse_args()
    if args.cmd == "init":
        init_db()
        print("Banco pronto: postgres" if using_postgres() else f"Banco pronto: {DB_PATH}")
    elif args.cmd == "products":
        cmd_products(args)
    elif args.cmd == "create":
        cmd_create(args)
    elif args.cmd == "renew":
        cmd_renew(args)
    elif args.cmd == "block":
        cmd_status(args, "blocked")
    elif args.cmd == "unblock":
        cmd_status(args, "active")
    elif args.cmd == "list":
        cmd_list(args)
    elif args.cmd == "usage":
        cmd_usage(args)
    elif args.cmd == "serve":
        cmd_serve(args)


if __name__ == "__main__":
    main()
